name: Build WordPress stubs

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-stubs:
        runs-on: ubuntu-latest
        steps:

            -   name: Setup SSH
                uses: webfactory/ssh-agent@v0.8.0
                with:
                    ssh-private-key: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}
                  
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    ssh-key: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   name: Install dependencies
                uses: ramsey/composer-install@v2

            -   name: Generate stubs
                run: php generate.php

            -   name: Add, commit, and push
                run: |
                    git config user.email ${{ secrets.DEPLOYBOT_EMAIL }}
                    git config user.name ${{ secrets.DEPLOYBOT_USER }}
                    git config --add safe.directory "${GITHUB_WORKSPACE}"
                    git add ./stubs/*
                    git add ./packages.json
                    git commit -m "Update WordPress stubs" || echo 'Nothing to commit'
                    git push
